<?php

return [
    'it-passport' => [
        'category' => 'national',
        'rank' => 1,
        'category_rank' => 1,
        'name' => 'ITパスポート試験',
        'short_name' => 'ITパスポート',
        'code' => 'IP',
        'level' => '国家試験 レベル1',
        'description' => '社会人・学生を含む幅広い受験者向け。IT、経営、マネジメントの基礎を横断的に確認します。',
    ],
    'fundamental-engineer' => [
        'category' => 'national',
        'rank' => 2,
        'category_rank' => 2,
        'name' => '基本情報技術者試験',
        'short_name' => '基本情報',
        'code' => 'FE',
        'level' => '国家試験 レベル2',
        'description' => 'ITエンジニアの基礎力を測る試験。アルゴリズム、セキュリティ、ネットワーク、データベースを重点的に扱います。',
    ],
    'applied-engineer' => [
        'category' => 'national',
        'rank' => 3,
        'category_rank' => 3,
        'name' => '応用情報技術者試験',
        'short_name' => '応用情報',
        'code' => 'AP',
        'level' => '国家試験 レベル3',
        'description' => '設計、運用、マネジメント、ストラテジまで含めて、実務で使える応用力を確認します。',
    ],
    'security-management' => [
        'category' => 'national',
        'rank' => 4,
        'category_rank' => 4,
        'name' => '情報セキュリティマネジメント試験',
        'short_name' => 'セキュマネ',
        'code' => 'SG',
        'level' => '国家試験 レベル2',
        'description' => '組織の情報セキュリティ管理、リスク対応、インシデント対応の基礎を固めます。',
    ],
    'registered-security-specialist' => [
        'category' => 'national',
        'rank' => 5,
        'category_rank' => 5,
        'name' => '情報処理安全確保支援士試験',
        'short_name' => '支援士',
        'code' => 'SC',
        'level' => '国家試験 レベル4',
        'description' => '高度なセキュリティ設計、脆弱性、暗号、運用管理、インシデント対応を扱います。',
    ],
    'aws-cloud-practitioner' => [
        'category' => 'vendor',
        'rank' => 6,
        'category_rank' => 1,
        'name' => 'AWS Certified Cloud Practitioner',
        'short_name' => 'AWS CLF',
        'code' => 'CLF-C02',
        'level' => 'ベンダー資格 基礎',
        'description' => 'AWSクラウドの価値、責任共有モデル、主要サービス、料金、セキュリティを確認します。',
    ],
    'azure-fundamentals' => [
        'category' => 'vendor',
        'rank' => 7,
        'category_rank' => 2,
        'name' => 'Microsoft Certified: Azure Fundamentals',
        'short_name' => 'Azure Fundamentals',
        'code' => 'AZ-900',
        'level' => 'ベンダー資格 基礎',
        'description' => 'Azureのクラウド概念、主要サービス、管理、ガバナンス、料金体系を確認します。',
    ],
    'ccna' => [
        'category' => 'vendor',
        'rank' => 8,
        'category_rank' => 3,
        'name' => 'Cisco Certified Network Associate',
        'short_name' => 'CCNA',
        'code' => '200-301',
        'level' => 'ベンダー資格 アソシエイト',
        'description' => 'ネットワーク基礎、IP接続、セキュリティ基礎、自動化、Cisco機器の考え方を確認します。',
    ],
    'comptia-security-plus' => [
        'category' => 'vendor',
        'rank' => 9,
        'category_rank' => 4,
        'name' => 'CompTIA Security+',
        'short_name' => 'Security+',
        'code' => 'SY0-701',
        'level' => 'ベンダーニュートラル セキュリティ',
        'description' => '脅威、脆弱性、セキュリティ運用、アーキテクチャ、リスク管理の基礎を確認します。',
    ],
    'google-cloud-digital-leader' => [
        'category' => 'vendor',
        'rank' => 10,
        'category_rank' => 5,
        'name' => 'Google Cloud Cloud Digital Leader',
        'short_name' => 'Cloud Digital Leader',
        'code' => 'CDL',
        'level' => 'ベンダー資格 基礎',
        'description' => 'Google Cloudの価値、データ、AI、インフラ、セキュリティ、運用の基礎を確認します。',
    ],
    'mos' => [
        'category' => 'private',
        'rank' => 11,
        'category_rank' => 1,
        'name' => 'Microsoft Office Specialist',
        'short_name' => 'MOS',
        'code' => 'MOS',
        'level' => '民間IT資格 オフィス実務',
        'description' => 'Word、Excel、PowerPointなどの実務操作力を測る国際資格です。',
    ],
    'itil-foundation' => [
        'category' => 'private',
        'rank' => 12,
        'category_rank' => 2,
        'name' => 'ITIL 4 Foundation',
        'short_name' => 'ITIL Foundation',
        'code' => 'ITIL4',
        'level' => '民間IT資格 ITサービス管理',
        'description' => 'ITサービスマネジメントの基本概念、価値共創、サービスバリューシステムを確認します。',
    ],
    'comptia-a-plus' => [
        'category' => 'private',
        'rank' => 13,
        'category_rank' => 3,
        'name' => 'CompTIA A+',
        'short_name' => 'A+',
        'code' => 'A+',
        'level' => '民間IT資格 ITサポート',
        'description' => 'PC、OS、モバイル、ネットワーク、セキュリティ、トラブルシューティングの基礎を確認します。',
    ],
    'comptia-network-plus' => [
        'category' => 'private',
        'rank' => 14,
        'category_rank' => 4,
        'name' => 'CompTIA Network+',
        'short_name' => 'Network+',
        'code' => 'N10',
        'level' => '民間IT資格 ネットワーク',
        'description' => 'ネットワーク設計、運用、トラブルシューティング、セキュリティ基礎を確認します。',
    ],
    'linuc-level1' => [
        'category' => 'private',
        'rank' => 15,
        'category_rank' => 5,
        'name' => 'LinuC レベル1',
        'short_name' => 'LinuC Lv1',
        'code' => 'LinuC-1',
        'level' => '民間IT資格 Linux',
        'description' => 'Linuxサーバーの基本操作、ファイル管理、ユーザー管理、ネットワーク基礎を確認します。',
    ],
];
